Start Agent init....
Entered Push Env
Entered Moveo Env
[ INFO] [1627887485.162948955]: Loading robot model 'moveo_description'...
[ INFO] [1627887485.163709386]: No root/virtual joint specified in SRDF. Assuming fixed joint
###### Setting Group Moveit with 30 seconds wait...
[ INFO] [1627887486.472442770, 105.777000000]: Ready to take commands for planning group arm.
<class 'moveo_commander.MoveoCommander'>
launch the init function of the Parent Class robot_gazebo_env_goal.RobotGazeboEnv.....
Entered Gazebo Env
False
launch the init function of the Parent Class robot_gazebo_env_goal.RobotGazeboEnv.....END
Entered Moveo Env END
START Actor init
END Actor init....
NUMBER OF WORKERS=CPUs available for this training=1
END Agent init....
Entered Push Env
[31m[ERROR] [1627887486.496158, 105.796000]: NOT Initialising Simulation Physics Parameters
[33m[WARN] [1627887486.508391, 105.803000]: Start Init ControllersConnection
[33m[WARN] [1627887486.510058, 105.803000]: END Init ControllersConnection
/home/nils/anaconda3/envs/moveo_training/lib/python3.9/site-packages/gym/logger.py:30: UserWarning: [33mWARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
2021-08-02 08:58:06.707836: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
Entered Moveo Env
###### Setting Group Moveit with 30 seconds wait...
[ INFO] [1627887487.263891145, 106.453000000]: Ready to take commands for planning group arm.
<class 'moveo_commander.MoveoCommander'>
launch the init function of the Parent Class robot_gazebo_env_goal.RobotGazeboEnv.....
Entered Gazebo Env
False
launch the init function of the Parent Class robot_gazebo_env_goal.RobotGazeboEnv.....END
Entered Moveo Env END
Start Worker Agent init....
START Actor init
END Actor init....
END Worker Agent init....
####################### START Train
####################### START AC3
EP0 EpisodeReward=0
Entered reset
0.0
0.0
0.0
0.0
0.0
[ INFO] [1627887488.111303953, 107.260000000]: ABORTED: Solution found but controller failed during execution
Entered step
Unpause sim
Set action
Action:
[-0.06391644  0.62359146  1.10501903  0.38172901  0.96951006]
-0.06391644432712629
0.6235914632771992
1.1050190342845871
0.38172900797586407
0.9695100642703803
2021-08-02 08:58:06.709145: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-08-02 08:58:06.711062: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
[31m[ERROR] [1627887487.296527, 106.482000]: NOT Initialising Simulation Physics Parameters
[33m[WARN] [1627887487.314018, 106.496000]: Start Init ControllersConnection
[33m[WARN] [1627887487.315248, 106.496000]: END Init ControllersConnection
2021-08-02 08:58:08.205183: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-08-02 08:58:08.222374: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 3192450000 Hz
[ INFO] [1627887499.964315056, 118.978000000]: ABORTED: Solution found but controller failed during execution
Get Obs
Exception in thread Thread-23:
Traceback (most recent call last):
  File "/home/nils/anaconda3/envs/moveo_training/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/nils/Documents/Studium/Bachelorarbeit/moveo_RL/src/moveo_training/scripts/A3C_Continuous_moveo.py", line 299, in run
    self.train()
  File "/home/nils/Documents/Studium/Bachelorarbeit/moveo_RL/src/moveo_training/scripts/A3C_Continuous_moveo.py", line 252, in train
    next_state, reward, done, _ = self.env.step(action)
  File "/home/nils/anaconda3/envs/moveo_training/lib/python3.9/site-packages/gym/wrappers/time_limit.py", line 16, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/nils/Documents/Studium/Bachelorarbeit/moveo_RL/src/openai_ros/openai_ros/src/openai_ros/robot_gazebo_env_goal.py", line 51, in step
    obs = self._get_obs()
  File "/home/nils/Documents/Studium/Bachelorarbeit/moveo_RL/src/moveo_training/scripts/moveo_push.py", line 132, in _get_obs
    self.gazebo.unpauseSim()
  File "/home/nils/Documents/Studium/Bachelorarbeit/moveo_RL/src/openai_ros/openai_ros/src/openai_ros/gazebo_connection.py", line 58, in unpauseSim
    rospy.wait_for_service('/gazebo/unpause_physics')
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 166, in wait_for_service
    raise ROSInterruptException("rospy shutdown")
rospy.exceptions.ROSInterruptException: rospy shutdown